services:
  web:
    build:
      context: ./apps/client
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3001
    ports:
      - 3000:3000
  server:
    build: ./apps/server
    ports:
      - 3001:3001
    env_file:
      - .env.server.local
