services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3001
    ports:
      - 3000:3000
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3001:3001
    env_file:
      - .env.server.local
