# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker images to Docker Hub

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 1 * *"

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ GITHUB_REF_NAME }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ajeje93/meme-game-client:latest
      
      - name: Build and push Docker server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ajeje93/meme-game-server:latest
